const API_URL_BASE = "https://localhost:7182/api";

const PRODUCT_ENDPOINTS = {
    GET_ALL_PRODUCTS: 'Product'
};

const WAREHOUSE_ENDPOINTS = {
    GET_ALL_WAREHOUSES: 'Warehouse'
};

const TRANSACTION_ENDPOINTS = {
    GET_ALL_TRANSACTIONS: 'Transaction'
};

const API_URL_FULL = {
    API_URL_GET_ALL_PRODUCTS: `${API_URL_BASE}/${PRODUCT_ENDPOINTS.GET_ALL_PRODUCTS}`,
    API_URL_GET_ALL_WAREHOUSES: `${API_URL_BASE}/${WAREHOUSE_ENDPOINTS.GET_ALL_WAREHOUSES}`,
    API_URL_GET_ALL_TRANSACTIONS: `${API_URL_BASE}/${TRANSACTION_ENDPOINTS.GET_ALL_TRANSACTIONS}`
};

const Constants = API_URL_FULL;
export default Constants;