const API_URL_BASE = 'https://localhost:7182/api/';

const ENDPOINTS = {
  GET_ALL_PRODUCTS: 'Product',
  GET_ALL_WAREHOUSES: 'Warehouse',
  GET_ALL_TRANSACTIONS: 'Transaction',
  GET_ALL_PRODUCTS_ON_DATE: 'Report',
};

export const API_URL_GET_ALL_PRODUCTS = `${API_URL_BASE}${ENDPOINTS.GET_ALL_PRODUCTS}`;
export const API_URL_GET_ALL_WAREHOUSES = `${API_URL_BASE}${ENDPOINTS.GET_ALL_WAREHOUSES}`;
export const API_URL_GET_ALL_TRANSACTIONS = `${API_URL_BASE}${ENDPOINTS.GET_ALL_TRANSACTIONS}`;
export const API_URL_GET_ALL_PRODUCTS_ON_DATE = `${API_URL_BASE}${ENDPOINTS.GET_ALL_PRODUCTS_ON_DATE}`;
